# Generated by Django 4.2.4 on 2023-08-12 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensions', models.TextField()),
                ('model_number', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
                ('asin', models.CharField(max_length=50, unique=True)),
                ('country_of_origin', models.CharField(max_length=50)),
                ('seller_rank', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(max_length=50)),
                ('stock', models.PositiveBigIntegerField(default=0)),
                ('style', models.CharField(choices=[('DE', 'Designer Edition'), ('LE', 'Limited Edition'), ('FE', 'Factory Edition')], default='DE', max_length=2)),
                ('image', models.ImageField(upload_to='product/images')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category')),
                ('details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.details')),
            ],
        ),
    ]
