# Generated by Django 4.2.4 on 2023-08-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='dimensions',
            field=models.CharField(max_length=50),
        ),
    ]
