# Generated by Django 5.2.1 on 2025-05-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('brand', models.CharField(max_length=255, verbose_name='Brand')),
                ('sku_code', models.CharField(max_length=255, verbose_name='SKU Code')),
                ('product_summary', models.TextField(verbose_name='AI Summary Description')),
                ('currency', models.CharField(default='KES', max_length=255, verbose_name='Currency')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
            ],
        ),
    ]
