# Generated by Django 5.2.1 on 2025-05-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailmodel',
            name='category',
            field=models.CharField(default='', max_length=255, verbose_name='Currency'),
        ),
    ]
