# Generated by Django 5.2.1 on 2025-05-26 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_detailmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailmodel',
            name='category',
        ),
    ]
