# Generated by Django 5.2.1 on 2025-05-26 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_categorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product_app.categorymodel'),
        ),
    ]
