# Generated by Django 5.2.1 on 2025-05-26 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_detailmodel_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name': 'Category Model', 'verbose_name_plural': 'Category Models'},
        ),
        migrations.AlterModelOptions(
            name='detailmodel',
            options={'verbose_name': 'Detail Model', 'verbose_name_plural': 'Detail Models'},
        ),
    ]
