# Generated by Django 5.2.1 on 2025-05-26 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_alter_categorymodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=255, verbose_name='Sub Category')),
            ],
            options={
                'verbose_name': 'Sub Category Model',
                'verbose_name_plural': 'Sub Category Models',
            },
        ),
        migrations.RemoveField(
            model_name='categorymodel',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='detailmodel',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product_app.subcategorymodel'),
        ),
    ]
