# Generated by Django 5.2.1 on 2025-05-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0008_alter_categorymodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='category',
            field=models.CharField(max_length=255, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='subcategorymodel',
            name='sub_category',
            field=models.CharField(max_length=255, verbose_name='Sub Category'),
        ),
    ]
