# Generated by Django 5.2.1 on 2025-05-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0009_alter_categorymodel_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_photos', models.ImageField(upload_to='product_photos/')),
            ],
            options={
                'verbose_name': 'Photos Model',
                'verbose_name_plural': 'Photos Models',
            },
        ),
        migrations.CreateModel(
            name='VideosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_videos', models.FileField(upload_to='product_photos/')),
            ],
            options={
                'verbose_name': 'Video Model',
                'verbose_name_plural': 'Video Models',
            },
        ),
    ]
