# Generated by Django 5.2.1 on 2025-05-28 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0010_photosmodel_videosmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailmodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='detailmodel',
            name='sub_category',
        ),
    ]
