# Generated by Django 5.2.1 on 2025-05-29 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0013_remove_productfile_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='detailmodel',
            options={'verbose_name': 'Detail', 'verbose_name_plural': 'Details'},
        ),
        migrations.AlterModelOptions(
            name='photosmodel',
            options={'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
        migrations.AlterModelOptions(
            name='subcategorymodel',
            options={'verbose_name': 'Sub Category', 'verbose_name_plural': 'Sub Categories'},
        ),
        migrations.AlterModelOptions(
            name='videosmodel',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
    ]
