# Generated by Django 5.2.1 on 2025-05-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0015_brandmodel_remove_detailmodel_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowRatingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_star_ratings', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Average Star Ratings')),
                ('five_star_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='5 Star Rating')),
                ('four_star_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='4 Star Rating')),
                ('three_star_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='3 Star Rating')),
                ('two_star_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='2 Star Rating')),
                ('one_star_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='1 Star Rating')),
            ],
            options={
                'verbose_name': 'Star Rating',
                'verbose_name_plural': 'Star Ratings',
            },
        ),
        migrations.AlterField(
            model_name='videosmodel',
            name='product_videos',
            field=models.FileField(blank=True, null=True, upload_to='Product_Videos/'),
        ),
    ]
