# Generated by Django 5.2.1 on 2025-05-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0016_showratingmodel_alter_videosmodel_product_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews_count', models.IntegerField(blank=True, null=True, verbose_name='Review Count')),
            ],
            options={
                'verbose_name': 'Review Count',
                'verbose_name_plural': 'Reviews Count',
            },
        ),
    ]
