# Generated by Django 5.2.1 on 2025-05-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0018_inventorymetermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_1_selector', models.CharField(max_length=255, verbose_name='Option 1 Selector')),
                ('option_2_selector', models.CharField(max_length=255, verbose_name='Option 2 Selector')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
            },
        ),
    ]
