# Generated by Django 5.2.1 on 2025-05-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0019_optionsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_list', models.CharField(max_length=255, verbose_name='Tags List')),
            ],
            options={
                'verbose_name': 'Tags List',
                'verbose_name_plural': 'Tags Lists',
            },
        ),
    ]
