# Generated by Django 5.2.1 on 2025-05-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0022_specificationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option1Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_1_selector', models.CharField(max_length=255, verbose_name='Option 1 Selector')),
            ],
            options={
                'verbose_name': 'Option 1',
                'verbose_name_plural': 'Options 1',
            },
        ),
        migrations.CreateModel(
            name='Option2Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_2_selector', models.CharField(max_length=255, verbose_name='Option 2 Selector')),
            ],
            options={
                'verbose_name': 'Option 2',
                'verbose_name_plural': 'Options 2',
            },
        ),
        migrations.DeleteModel(
            name='OptionsModel',
        ),
    ]
