# Generated by Django 5.2.1 on 2025-06-02 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0024_summarydescriptionmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summarydescriptionmodel',
            options={'verbose_name': 'Summary Description', 'verbose_name_plural': 'Summary Descriptions'},
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product_app.brandmodel', verbose_name='Brand')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product_app.categorymodel', verbose_name='Category')),
                ('description', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product_app.descriptionmodel', verbose_name='Description')),
                ('detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product_app.detailmodel', verbose_name='Detail')),
                ('inventory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product_app.inventorymetermodel', verbose_name='Inventory Meter')),
                ('option1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product_app.option1model', verbose_name='Option 1')),
                ('option2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product_app.option2model', verbose_name='Option 2')),
                ('photos', models.ManyToManyField(to='product_app.photosmodel', verbose_name='Photos')),
                ('rating', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product_app.showratingmodel', verbose_name='Star Rating')),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product_app.reviewmodel', verbose_name='Review')),
                ('specification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product_app.specificationmodel', verbose_name='Specification')),
                ('sub_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product_app.subcategorymodel', verbose_name='Sub Category')),
                ('summary_description', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product_app.summarydescriptionmodel', verbose_name='Summary Description')),
                ('tags', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product_app.tagsmodel', verbose_name='Tags List')),
                ('videos', models.ManyToManyField(to='product_app.videosmodel', verbose_name='Videos')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
