# Generated by Django 5.2.1 on 2025-06-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0025_alter_summarydescriptionmodel_options_productmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductModel',
        ),
    ]
