# Generated by Django 4.2.4 on 2023-09-28 06:31

from django.db import migrations, models
import django.utils.timezone
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='addr1',
            field=models.TextField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='addr2',
            field=models.TextField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='addr_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789abcdefABCDEF', length=10, max_length=20, prefix='address-', unique=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='city',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='country',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='phonenumber_primary',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='phonenumber_secondary',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='account_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='pay_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789abcdefABCDEF', length=10, max_length=20, prefix='payment-', unique=True),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='provider',
            field=models.CharField(default='--None--', max_length=100),
        ),
    ]
