# Generated by Django 4.2.4 on 2023-09-16 23:01

import customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=customer.models.admin_image_directory),
        ),
    ]
