# Generated by Django 4.2.4 on 2023-09-28 14:36

import customer.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_UserAddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev_id', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789abcdefABCDEF', length=10, max_length=20, prefix='review', unique=True)),
                ('review_title', models.CharField(default='Great Product', max_length=50)),
                ('review_screenshots', models.ImageField(blank=True, default=None, null=True, upload_to=customer.models.admin_image_directory)),
                ('review_text', models.CharField(default='I love the product', max_length=1000)),
                ('review_rating', models.CharField(choices=[('⭐⭐⭐⭐⭐', 5), ('⭐⭐', 2), ('⭐⭐⭐', 3), ('⭐⭐⭐⭐', 4), ('⭐', 1)], default='--NONE---', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='product_rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.productreview'),
        ),
    ]
