# Generated by Django 4.2.4 on 2023-09-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_productreview_customuser_product_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'verbose_name': 'Product Review', 'verbose_name_plural': 'Product Reviews'},
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_rating',
            field=models.CharField(choices=[('⭐', 1), ('⭐⭐⭐⭐⭐', 5), ('⭐⭐⭐⭐', 4), ('⭐⭐⭐', 3), ('⭐⭐', 2)], default='--NONE---', max_length=50),
        ),
    ]
