# Generated by Django 4.2.4 on 2023-09-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_productreview_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='review_rating',
            field=models.CharField(choices=[('⭐⭐⭐⭐⭐', 5), ('⭐⭐⭐⭐', 4), ('⭐⭐', 2), ('⭐', 1), ('⭐⭐⭐', 3)], default='--NONE---', max_length=50),
        ),
    ]
