# Generated by Django 4.2.4 on 2023-09-29 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_remove_customuser_product_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='review_rating',
            field=models.CharField(choices=[('⭐⭐', 2), ('⭐', 1), ('⭐⭐⭐⭐⭐', 5), ('⭐⭐⭐', 3), ('⭐⭐⭐⭐', 4)], default='------', max_length=50),
        ),
        migrations.CreateModel(
            name='ProductOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_id', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789abcdefABCDEF', length=10, max_length=20, prefix='', unique=True)),
                ('item_number', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Completed', 'paid'), ('Ongoing', 'ongoing'), ('Pending', 'pending'), ('Cancelled', 'cancelled')], default='-------', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orders',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
