# Generated by Django 4.2.4 on 2023-09-26 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 9, 26, 8, 32, 9, 216427, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 9, 26, 8, 32, 9, 214428, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='discount',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 9, 26, 8, 32, 9, 215427, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 9, 26, 8, 32, 9, 215427, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='shoppingsession',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 9, 26, 8, 32, 9, 216427, tzinfo=datetime.timezone.utc)),
        ),
    ]
