# Generated by Django 4.2.4 on 2023-09-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_choice',
            field=models.CharField(choices=[('Home & Kitchen', 'Home'), ('Luggage', 'Luggage'), ('Baby Products', 'Baby'), ("Men's Fashion", 'Men'), ("Women's Fashion", 'Women'), ('Beauty & Personal Care', 'Beauty'), ('Automotive', 'Auto'), ('Pet Supplies', 'Pet'), ('Health & Household', 'Health')], default='--select--', max_length=50),
        ),
    ]
