# Generated by Django 4.2.4 on 2023-09-28 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_productreview_review_rating'),
        ('product', '0002_alter_category_category_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.productreview'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_choice',
            field=models.CharField(choices=[("Men's Fashion", 'Men'), ('Pet Supplies', 'Pet'), ('Home & Kitchen', 'Home'), ('Automotive', 'Auto'), ("Women's Fashion", 'Women'), ('Luggage', 'Luggage'), ('Baby Products', 'Baby'), ('Health & Household', 'Health'), ('Beauty & Personal Care', 'Beauty')], default='--select--', max_length=50),
        ),
    ]
