# Generated by Django 4.2.4 on 2023-09-26 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_cartitem_created_at_alter_category_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 9, 26, 8, 35, 38, 220052, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 9, 26, 8, 35, 38, 218054, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='discount',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 9, 26, 8, 35, 38, 219054, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 9, 26, 8, 35, 38, 219054, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='shoppingsession',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 9, 26, 8, 35, 38, 220052, tzinfo=datetime.timezone.utc)),
        ),
    ]
