# Generated by Django 4.2.4 on 2023-09-28 15:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import product.models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_review_alter_category_category_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_id', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789abcdefABCDEF', length=10, max_length=20, prefix='image-', unique=True)),
                ('image', models.ImageField(upload_to=product.models.product_directory_path)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.RemoveField(
            model_name='image',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='shoppingsession',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='review',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_choice',
            field=models.CharField(choices=[('Automotive', 'Auto'), ('Health & Household', 'Health'), ('Pet Supplies', 'Pet'), ('Home & Kitchen', 'Home'), ("Women's Fashion", 'Women'), ("Men's Fashion", 'Men'), ('Beauty & Personal Care', 'Beauty'), ('Luggage', 'Luggage'), ('Baby Products', 'Baby')], default='--select--', max_length=50),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ShoppingSession',
        ),
        migrations.AddField(
            model_name='productimage',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product'),
        ),
    ]
