# Generated by Django 4.2.4 on 2023-09-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productimage_remove_image_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_choice',
            field=models.CharField(choices=[('Health & Household', 'Health'), ('Baby Products', 'Baby'), ('Automotive', 'Auto'), ('Beauty & Personal Care', 'Beauty'), ('Pet Supplies', 'Pet'), ('Luggage', 'Luggage'), ('Home & Kitchen', 'Home'), ("Women's Fashion", 'Women'), ("Men's Fashion", 'Men')], default='--select--', max_length=50),
        ),
    ]
