# Generated by Django 4.2.4 on 2023-10-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_category_category_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_choice',
            field=models.CharField(choices=[('Beauty & Personal Care', 'Beauty'), ('Luggage', 'Luggage'), ("Women's Fashion", 'Women'), ('Baby Products', 'Baby'), ('Home & Kitchen', 'Home'), ('Automotive', 'Auto'), ("Men's Fashion", 'Men'), ('Pet Supplies', 'Pet'), ('Health & Household', 'Health')], default='--select--', max_length=50),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
