# Generated by Django 4.2.4 on 2023-10-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_category_category_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_choice',
            field=models.CharField(choices=[('Home & Kitchen', 'Home'), ('Baby Products', 'Baby'), ('Beauty & Personal Care', 'Beauty'), ('Luggage', 'Luggage'), ('Health & Household', 'Health'), ('Pet Supplies', 'Pet'), ("Men's Fashion", 'Men'), ("Women's Fashion", 'Women'), ('Automotive', 'Auto')], default='--select--', max_length=50),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_rating',
            field=models.CharField(choices=[('⭐⭐⭐', 3), ('⭐⭐', 2), ('⭐⭐⭐⭐⭐', 5), ('⭐', 1), ('⭐⭐⭐⭐', 4)], default='------', max_length=50),
        ),
    ]
