# Generated by Django 4.2.4 on 2023-10-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_category_category_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_choice',
            field=models.CharField(choices=[("Women's Fashion", 'Women'), ('Luggage', 'Luggage'), ('Automotive', 'Auto'), ('Beauty & Personal Care', 'Beauty'), ('Pet Supplies', 'Pet'), ("Men's Fashion", 'Men'), ('Health & Household', 'Health'), ('Home & Kitchen', 'Home'), ('Baby Products', 'Baby')], default='--select--', max_length=50),
        ),
    ]
