# Generated by Django 4.2.4 on 2023-10-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_category_category_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_choice',
            field=models.CharField(choices=[("Women's Fashion", 'Women'), ('Health & Household', 'Health'), ('Baby Products', 'Baby'), ('Beauty & Personal Care', 'Beauty'), ('Pet Supplies', 'Pet'), ('Automotive', 'Auto'), ('Luggage', 'Luggage'), ('Home & Kitchen', 'Home'), ("Men's Fashion", 'Men')], default='--select--', max_length=50),
        ),
    ]
