# Generated by Django 4.2.4 on 2023-10-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_category_category_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_choice',
            field=models.CharField(choices=[('Pet Supplies', 'Pet'), ('Home & Kitchen', 'Home'), ('Luggage', 'Luggage'), ('Baby Products', 'Baby'), ('Automotive', 'Auto'), ('Health & Household', 'Health'), ("Women's Fashion", 'Women'), ('Beauty & Personal Care', 'Beauty'), ("Men's Fashion", 'Men')], default='--select--', max_length=50),
        ),
    ]
