# Generated by Django 4.2.4 on 2023-09-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
