# Generated by Django 4.2.4 on 2023-09-26 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '__first__'),
        ('vendors', '0003_alter_vendor_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product'),
        ),
    ]
